#!/bin/bash

if [ "$1" == "sfp0" ] && [ "$2" == "up" ]; then
  # ethtool -K "$1" rx off gro off lro off
  # ethtool -K wan0 rx-udp-gro-forwarding on rx-gro-list off
  ethtool -K "$1" rx-udp-gro-forwarding on rx-gro-list off
fi
